/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package iCua.Activities;

public final class R {
    public static final class anim {
        public static final int fade=0x7f040000;
        public static final int layout_bottom_to_top_slide=0x7f040001;
        public static final int layout_grid_fade=0x7f040002;
        public static final int layout_grid_inverse_fade=0x7f040003;
        public static final int magnify=0x7f040004;
        public static final int magnify2=0x7f040005;
        public static final int slide_right=0x7f040006;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int i1=0x7f020000;
        public static final int i2=0x7f020001;
        public static final int i3=0x7f020002;
        public static final int i4=0x7f020003;
        public static final int i5=0x7f020004;
        public static final int i6=0x7f020005;
        public static final int i7=0x7f020006;
        public static final int i8=0x7f020007;
        public static final int i9=0x7f020008;
        public static final int icon=0x7f020009;
        public static final int loading=0x7f02000a;
        public static final int logo=0x7f02000b;
        public static final int logo1=0x7f02000c;
        public static final int media_playback_pause=0x7f02000d;
        public static final int media_playback_start=0x7f02000e;
        public static final int media_playback_stop=0x7f02000f;
        public static final int media_skip_backward=0x7f020010;
        public static final int media_skip_forward=0x7f020011;
        public static final int orange_logo_en=0x7f020012;
        public static final int pause=0x7f020013;
        public static final int pn=0x7f020014;
        public static final int stop=0x7f020015;
    }
    public static final class id {
        public static final int AbsoluteLayout01=0x7f070013;
        public static final int BPLCancel=0x7f070007;
        public static final int BPLSave=0x7f070006;
        public static final int Button01=0x7f070009;
        public static final int Button02=0x7f07000a;
        public static final int ButtonTune=0x7f070012;
        public static final int EditRadio=0x7f070010;
        public static final int EditText01=0x7f070008;
        public static final int GridView01=0x7f070017;
        public static final int ImageView01=0x7f070001;
        public static final int LinearLayout01=0x7f070000;
        public static final int LinearLayout02=0x7f070016;
        public static final int RadioArtist=0x7f07000c;
        public static final int RadioGroupLast=0x7f07000b;
        public static final int RadioTag=0x7f07000d;
        public static final int TableLayout01=0x7f070020;
        public static final int TableLayout02=0x7f070022;
        public static final int TableRow02=0x7f070021;
        public static final int TableRow03=0x7f07000e;
        public static final int TableRow04=0x7f070011;
        public static final int TextView01=0x7f070002;
        public static final int TextView02=0x7f07000f;
        public static final int container=0x7f070005;
        public static final int cover=0x7f070019;
        public static final int icon=0x7f070014;
        public static final int next=0x7f07001c;
        public static final int pause=0x7f07001d;
        public static final int playlist_edit=0x7f070004;
        public static final int playlist_view=0x7f070003;
        public static final int prev=0x7f07001b;
        public static final int slider=0x7f07001e;
        public static final int stop=0x7f07001f;
        public static final int text=0x7f070015;
        public static final int txt=0x7f07001a;
        public static final int widget0=0x7f070018;
    }
    public static final class layout {
        public static final int about=0x7f030000;
        public static final int alert_dialog_text_entry=0x7f030001;
        public static final int animations_main_screen=0x7f030002;
        public static final int contentplaylists=0x7f030003;
        public static final int editplaylist=0x7f030004;
        public static final int lastradio=0x7f030005;
        public static final int list_item_icon_text=0x7f030006;
        public static final int list_position=0x7f030007;
        public static final int main=0x7f030008;
        public static final int onair=0x7f030009;
        public static final int onairradio=0x7f03000a;
        public static final int playlists=0x7f03000b;
    }
    public static final class string {
        public static final int About=0x7f050005;
        public static final int app_name=0x7f050001;
        public static final int hello=0x7f050000;
        public static final int remote_service_label=0x7f050004;
        public static final int remote_service_started=0x7f050002;
        public static final int remote_service_stopped=0x7f050003;
    }
    public static final class style {
        /**  Base application theme is the default theme. 
         */
        public static final int Theme=0x7f060000;
        /**  Variation on our application theme that forces a plain
        text style. 
         */
        public static final int Theme_notitle=0x7f060001;
    }
}
